name: Sync Fork EasyProxy

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync from upstream
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git remote remove upstream || true
          git remote add upstream https://github.com/LucaPora90/EasyProxy.git
          git fetch upstream

          git checkout main
          git reset --hard upstream/main

          git push origin main --force
